### PR TITLE
Get multiqc reports for input to dias batch

### PR DESCRIPTION
**Pull request by jethror1**
- add new function `dx_manage.get_multiqc_report` to find multiqc reports to provide as input to batch
- add unit tests for above
- minor fixes for incorrect return types
- update `configs/manually_selected.json` with 2 new CNV call job IDs

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/43)

### CODE REVIEW

**Review by kjwinfield — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/43)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`configs/manually_selected.json` line 10 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/43#-O3HoCZN3MGTPmfHxQIP:-O3HoCZN3MGTPmfHxQIQ:b-dban8x) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/e26894a8311fba41cc42d88eac07d309874f87a8/configs/manually_selected.json#L10)):*
> ```JSON
>         "project-GXZg0J04BXfPFFZYYFGz42bP": "job-GXbyZ104BXf8G5296g93bvx2",
>         "project-GjFx5VQ48q2Bj4BQ5ZgfZJQx": "job-GjGbV4848q2F8P0419V093vJ",
>         "project-GkQv26j4Q5Yzk2VjK9bXgxFb": "job-GkVKff84Q5YzYJPP8VK4v4P6"
> ```

need to also add
project-Gkjp3K04PyP8k9VKv3x919zQ:job-GkpZ6kj4PyP5xY9Xz0395Pgg
___
*[`tests/test_dx_manage.py` line 907 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/43#-O3HoaYX5qV2fxwnvtAH:-O3HoaYX5qV2fxwnvtAI:b-dfno3h) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/e26894a8311fba41cc42d88eac07d309874f87a8/tests/test_dx_manage.py#L907)):*
> ```Python
>         with self.subTest('correct folder'):
>             assert mock_find.call_args[1]['folder'] == '/output/240802'
> ```

is it worth also testing that no/multiple multiqc reports adds project to manual_review

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/43)* status: all files reviewed, 2 unresolved discussions (waiting on @kjwinfield)

___
*[`configs/manually_selected.json` line 10 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/43#-O3HoCZN3MGTPmfHxQIP:-O3I51I00sTg56mOIEHS:b-896fix) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/e26894a8311fba41cc42d88eac07d309874f87a8/configs/manually_selected.json#L10)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

need to also add
project-Gkjp3K04PyP8k9VKv3x919zQ:job-GkpZ6kj4PyP5xY9Xz0395Pgg
</blockquote></details>

Done.
___
*[`tests/test_dx_manage.py` line 907 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/43#-O3HoaYX5qV2fxwnvtAH:-O3I5KGU7e8e2pplWRQL:b-3w5qra) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/e26894a8311fba41cc42d88eac07d309874f87a8/tests/test_dx_manage.py#L907)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

is it worth also testing that no/multiple multiqc reports adds project to manual_review
</blockquote></details>

hmm good point, this is in run_reports.configure_inputs, which I realised doesn't have any tests, added an issue here to remind myself and will add them to another PR: https://github.com/eastgenomics/dias_reports_bulk_reanalysis/issues/45

**Review by kjwinfield — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/43)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by kjwinfield — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/43)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
