### PR TITLE
Unittest utils.parse_sample_identifiers

### PR DESCRIPTION
**Pull request by jethror1**
- adds unittests for `utils.parse_sample_identifiers`
- adds additional check for valid sample names when parsing

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/13)

### CODE REVIEW

**Review by mattgarner — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/13)* status: 1 of 2 files reviewed, all discussions resolved

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/13)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`bin/utils/utils.py` line 427 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/13#-Nz7KWjr4I8sxeeqTvJu:-Nz7KWjr4I8sxeeqTvJv:b6xpym1) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/3ca5ee3c4d080bc4f296901bc260b1bd29171465/bin/utils/utils.py#L427)):*
> ```Python
>     # basic sense check that we don't have anything named like X12345.xlsx
>     # that won't pass the below parsing
>     # TODO - decide if this should just be a warning and log or error
> ```

Error seems fine to me. We stopped making reports for new Xs a year ago.



_Code quote:_
```Python
TODO - decide if this should just be a warning and log or error
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/13)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

___
*[`bin/utils/utils.py` line 427 at r1](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/13#-Nz7KWjr4I8sxeeqTvJu:-Nz7q7tYE7DhjNgIqBfJ:b-896fix) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/3ca5ee3c4d080bc4f296901bc260b1bd29171465/bin/utils/utils.py#L427)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Error seems fine to me. We stopped making reports for new Xs a year ago.
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/13)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
