### PR TITLE
Refactor parallelised dxpy.find_data_objects calls

### PR DESCRIPTION
**Pull request by jethror1**
- refactor the duplicated parallelised dxpy.find_data_objects into single cleaner function `find_in_parallel()`
- fix cnv call job ID reference in project data
- handle failed batch jobs causing error to be raised on trying to access job output

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/6)

### CODE REVIEW

**Review by kjwinfield — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/6)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[`bin/utils/dx_manage.py` line 119 at r2](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/6#-Ny_Rzxx9nM_tqpAgBMM:-Ny_Rzxx9nM_tqpAgBMN:bo318dq) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/53aded9e0102c3f53b7ece88bd0f46e73ea54796/bin/utils/dx_manage.py#L119)):*
> ```Python
>             name=rf'{prefix}{"|".join(search_term)}{suffix}',
>             name_mode='regexp',
>             describe={'fields': {'name': True, 'archivalState': True, 'createdBy': True}}
> ```

could this be on multiple lines?

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/6)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kjwinfield)

___
*[`bin/utils/dx_manage.py` line 119 at r2](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/6#-Ny_Rzxx9nM_tqpAgBMM:-NyaC4d39JUwqUSo432W:b-896fix) ([raw file](https://github.com/eastgenomics/dias_reports_bulk_reanalysis/blob/53aded9e0102c3f53b7ece88bd0f46e73ea54796/bin/utils/dx_manage.py#L119)):*
<details><summary><i>Previously, kjwinfield (Katherine Winfield) wrote…</i></summary><blockquote>

could this be on multiple lines?
</blockquote></details>

Done.

**Review by kjwinfield — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/6)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

**Review by kjwinfield — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/dias_reports_bulk_reanalysis/6)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
